#!/usr/bin/env bash

host=$1
shift
script=$1
shift
ssh $host "bash -ls" -- <$script $@

# For testing locally instead of over ssh
#cd ~/Development/deploymentTest/$host
#bash -s < ~/Development/deployment/$script $@
