#!/usr/bin/env bash

host=$1
shift
script=$1
shift
ssh $host "cd ~/deployment; bash -s" -- <$script $@

# For testing locally instead of over ssh
#cd ~/Development/deploymentTest
#bash -s < ~/Development/deployment/$script $@
