#!/usr/bin/env bash

host=$1
shift
filename=$1
shift
ssh $host "tee $filename > /dev/null"
# Send file contents to stdin

# For testing locally instead of over ssh
#cd ~/Development/deploymentTest
#tee $filename > /dev/null
